// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUu7IpliIGTRzjNooxAguYpT-UQld23wo',
    appId: '1:25291663802:web:b410c723a1a32f31b81583',
    messagingSenderId: '25291663802',
    projectId: 'atlas-9978e',
    authDomain: 'atlas-9978e.firebaseapp.com',
    storageBucket: 'atlas-9978e.firebasestorage.app',
    measurementId: 'G-8QHTK1V79H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtAVUNFOfs0ZBZNL5lRVreLU5mMNqNwA',
    appId: '1:25291663802:android:38a8ed2e0f191c46b81583',
    messagingSenderId: '25291663802',
    projectId: 'atlas-9978e',
    storageBucket: 'atlas-9978e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdAm-b0SKYMGCDSU7V1GFlzCRH2D66Wt4',
    appId: '1:25291663802:ios:e5f7d68b3f51d716b81583',
    messagingSenderId: '25291663802',
    projectId: 'atlas-9978e',
    storageBucket: 'atlas-9978e.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdAm-b0SKYMGCDSU7V1GFlzCRH2D66Wt4',
    appId: '1:25291663802:ios:e5f7d68b3f51d716b81583',
    messagingSenderId: '25291663802',
    projectId: 'atlas-9978e',
    storageBucket: 'atlas-9978e.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUu7IpliIGTRzjNooxAguYpT-UQld23wo',
    appId: '1:25291663802:web:e72be3733063cba7b81583',
    messagingSenderId: '25291663802',
    projectId: 'atlas-9978e',
    authDomain: 'atlas-9978e.firebaseapp.com',
    storageBucket: 'atlas-9978e.firebasestorage.app',
    measurementId: 'G-VFB4MGY1J6',
  );
}
